### ISSUE TITLE
Proposal: Option to add tag to Pocket imports

### ISSUE THREAD

**Issue by gpanders** [shanedabes/poku#97]
Hello,

Would you be open to a PR that adds a new config option that adds a given tag to all Pocket imports? Something like

```bash
$ poku --consumer ... --access ... --tag pocket
```

This will add the `pocket` tag to all items imported from Pocket.

I can write the patch myself, but I wanted to make sure this is something you'd be interested in first.

Thanks for this awesome project!

**Comment by surskitt** [comment]
that sounds like a great addition!
